platform :ios, '7.0'

target 'CSStickyHeaderFlowLayoutDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods
  pod "CSStickyHeaderFlowLayout", :path => "../"
end
